### ISSUE TITLE
学习Less-看这篇就够了 | ToMoToes

### ISSUE THREAD

**Issue by Tomotoes** [Tomotoes/blog#1]
https://tomotoes.com/blog/posts/11b92833/ 

 Less,CSS,预处理器,前端

**Comment by lzzattack** [comment]
博主!!你的博客好帅啊!!
我本身会前端,请问还需要学些什么能做出这个??谢谢啦

**Comment by Tomotoes** [comment]
> @lzzattack
> 博主!!你的博客好帅啊!!
> 我本身会前端,请问还需要学些什么能做出这个??谢谢啦
> 

本网站使用 hexo 搭建，网站挂在 Coding Page，网上这方面的教程很多的，没什么难度。

**Comment by Tomotoes** [comment]
自己设计,live2d是借鉴
