### ISSUE TITLE
Hexo-入门篇 | ToMoToes

### ISSUE THREAD

**Issue by Tomotoes** [Tomotoes/blog#11]
https://tomotoes.com/blog/posts/b9fba72a/ 

 Hexo,个人博客

**Comment by Rainylo** [comment]
博主你好，我的hexo博客改好了，如何直接部署弄到云服务器里而不是github里啊？

**Comment by Tomotoes** [comment]
@Rainylo 不要思想固化，部署其实和 hexo 没有什么关系，hexo 只是你网站的生成器。
当你运行 `hexo g` 之后，你的网站内容就会被放到 根目录的 public 文件夹，而这个public 文件夹就是你网站的所有内容了。
你需要做的就是把一个保存着网站的文件夹上传到到云服务器上而已，当你买云服务器时，肯定会有相关的指导，再说了 网上相关的文章也会有很多的。
好运。

**Comment by Rainylo** [comment]
> @Tomotoes
> @Rainylo 不要思想固化，部署其实和 hexo 没有什么关系，hexo 只是你网站的生成器。
> 当你运行 `hexo g` 之后，你的网站内容就会被放到 根目录的 public 文件夹，而这个public 文件夹就是你网站的所有内容了。
> 你需要做的就是把一个保存着网站的文件夹上传到到云服务器上而已，当你买云服务器时，肯定会有相关的指导，再说了 网上相关的文章也会有很多的。
> 好运。

感谢你的回复，对我帮助很大，那如果，我将public放到云服务器里，之后更新文章是只需要把文章写好上传至相应文件夹里就可以了是吗

**Comment by Tomotoes** [comment]
1. 写好文章，生成到 public文件夹
2. 再将站点文件（public文件夹）更新到服务器
3. 服务器收到文件，一般会自动部署的
第一步，第二步 写个 sh 脚本 就够了，第三步 不是很了解，最好找点文章看看。
sh脚本：
```sh
hexo clean
hexo g
上传到服务器的命令
```
执行脚本 (命令行)
`./脚本名.sh`

**Comment by Rainylo** [comment]
你好，我还有一个问题，是在初始化gitalk时出现的：Error: Validation Failed.这个应该如何解决呢？

**Comment by Tomotoes** [comment]
谷歌或者去gitalk 的 Issues 看看

**Comment by Tomotoes** [comment]
就是每篇文章的头部进行声明,可以去hexo官网上进行查阅

**Comment by liuzhuo19940206** [comment]
博主，你的博客部署在哪里？我部署在github上面，感觉访问时，很慢，感觉你的很快

**Comment by Tomotoes** [comment]
> 博主，你的博客部署在哪里？我部署在github上面，感觉访问时，很慢，感觉你的很快

我的就是部署在 GithubPage 啊...
你的网站我看一下, 帮你分析一下 , 什么因素..

**Comment by liuzhuo19940206** [comment]
> @Tomotoes
> > 博主，你的博客部署在哪里？我部署在github上面，感觉访问时，很慢，感觉你的很快
> 
> 我的就是部署在 GithubPage 啊...
> 你的网站我看一下, 帮你分析一下 , 什么因素..

额，gakkil.top

**Comment by liuzhuo19940206** [comment]
https://gakkil.top/

**Comment by Tomotoes** [comment]
> https://gakkil.top/

我大致看了一下,你引用的文件有点多啊...
最好按需加载, 就是分页面加载 .
然后 脚本文件 , html , 图片都用 gulp 处理一下.
你可以利用 Google Aduits 来查看一下 你网站的优化建议, 网页控制台中就有.

你也可以把自己的静态文件 放到 jsDelivr 上面 
具体教程可以网上搜索

再看看有没有什么阻塞脚本...

嗯, 先这样..

**Comment by liuzhuo19940206** [comment]
> @Tomotoes
> > https://gakkil.top/
> 
> 我大致看了一下,你引用的文件有点多啊...
> 最好按需加载, 就是分页面加载 .
> 然后 脚本文件 , html , 图片都用 gulp 处理一下.
> 你可以利用 Google Aduits 来查看一下 你网站的优化建议, 网页控制台中就有.
> 
> 你也可以把自己的静态文件 放到 jsDelivr 上面 
> 具体教程可以网上搜索
> 
> 再看看有没有什么阻塞脚本...
> 
> 嗯, 先这样..

好的，谢谢大佬
