### ISSUE TITLE
记一次网站失踪的血案 | ToMoToes

### ISSUE THREAD

**Issue by Tomotoes** [Tomotoes/blog#14]
https://tomotoes.com/blog/posts/6d50930/ 

 网站丢失

**Comment by Spturate** [comment]
你这个live2d怎么和我的不一样，

**Comment by Tomotoes** [comment]
> @Spturate
> 你这个live2d怎么和我的不一样，

私人定制的呀

**Comment by Spturate** [comment]
> @Tomotoes
> > @Spturate
> > 你这个live2d怎么和我的不一样，
> 
> 私人定制的呀

要咋定制的，你做个教程好吗A.A

**Comment by clq2owesome** [comment]
鲜榨橙汁
