### ISSUE TITLE
你有所不知的margin属性 | ToMoToes

### ISSUE THREAD

**Issue by Tomotoes** [Tomotoes/blog#15]
https://tomotoes.com/blog/posts/88f6102c/ 

 margin,css,web

**Comment by xiaowang23** [comment]
#这个博文也太优雅了一点

**Comment by Tomotoes** [comment]
> @xiaowang23
> #这个博文也太优雅了一点

thanks.

**Comment by Xanadu-zs** [comment]
hhh~   精通 css   /手动滑稽
