### ISSUE TITLE
热乎乎的开源主页

### ISSUE THREAD

**Issue by Tomotoes** [Tomotoes/blog#27]
https://tomotoes.com/blog/posts/38bcb15f/

**Comment by peanutDD** [comment]
come on gogogo

**Comment by Tomotoes** [comment]
@peanutDD 👾👾👾

**Comment by lizhuangs** [comment]
没跑起来，要安装一些插件还是什么。我对右侧的目录树和文章里面的有序列表比较感兴趣，这是怎么实现的有教程么~

**Comment by Tomotoes** [comment]
@lizhuangs 怎么没跑起来? 哪里错了嘛? 开源主题中包含你感兴趣的

**Comment by lizhuangs** [comment]
之前用的next主题，很多标签不支持，比如note,tab,cq等。把这些都删除后报：Template render error: (unknown path) [Line 8, Column 25]
  Error: Unable to call `the return value of (posts["first"])["updated"]["toISOString"]`, which is undefined or falsey
    at Object._prettifyError (node_modules\nunjucks\src\lib.js:36:11)看不出来什么问题。
